### ISSUE TITLE
support for react-native 0.30.0

### ISSUE THREAD

**Issue by radiegtya** [Sitebase/react-avatar#42]
I got this error message:

```
Transform errror...
/node_modules/react-avatar/lib/index.js: Unknown plugin "add-module-exports" specified in "/Users/.../node_modules/react-avatar/.babelrc" at 0, attempted to...
```

**Comment by perrosnk** [comment]
When will this be fixed?

**Comment by Sitebase** [comment]
@radiegtya strange because this dependency is [in the package.json file](https://github.com/Sitebase/react-avatar/blob/master/package.json#L38).
Can you check your `node_modules` folder to see if there is a subfolder called `babel-plugin-add-module-exports`?

@perrosnk your problem doesn't seem related to this issue. Can you try the new version `2.2.1` version. If there is still an issue after the update, feel free to create an issue.

**Comment by perrosnk** [comment]
There wasn't any package in the node_module folder called babel-plugin-add-module-exports nor react-addons-shallow-compare.
So I run:
npm install --save react-addons-shallow-compare

npm install --save babel-plugin-add-module-exports

But then I had a problem with another package so I then run:
npm install --save babel-plugin-transform-runtime

But again, I had another problem, and it seems it never stops.

@Sitebase could you please help? Are you able to run it?

**Comment by Sitebase** [comment]
@perrosnk can you open a new issue for this because it's unrelated to this react-native issue.

**Comment by Sitebase** [comment]
I did a clean install

* remove `node_modules`
* run `npm install`
* run npm run dev

worked without a problem here.
Can you test these commands in your `react-avatar` folder? If that works the problem is probably a conflict with another library.

**Comment by perrosnk** [comment]
@Sitebase what version of react-native did you use?

**Comment by perrosnk** [comment]
@Sitebase 

1. I created a new project by running `react-native init testavatar`
2. I run `npm install --save react-avatar`
3. `react-native run-ios`. Till now the project runs fine.
the dependencies: 
`"dependencies": {
    "react": "15.3.2",
    "react-avatar": "^2.2.1",
    "react-native": "0.34.1"
  }`
3. Imported react-avatar into the file: `import {Avatar} from 'react-avatar'` and included it `<Avatar name="Wim Mostmans" size="150" />`

Now the project fails with this error:
`
> ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/perros/rn/testavatar/node_modules/react-avatar/.babelrc" at 0, attempted to resolve relative to "/Users/perros/rn/testavatar/node_modules/react-avatar"
>     at /Users/perros/rn/testavatar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
>     at Array.map (native)
>     at Function.normalisePlugins (/Users/perros/rn/testavatar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
>     at OptionManager.mergeOptions (/Users/perros/rn/testavatar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
>     at OptionManager.init (/Users/perros/rn/testavatar/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
>     at File.initOptions (/Users/perros/rn/testavatar/node_modules/babel-core/lib/transformation/file/index.js:221:65)
>     at new File (/Users/perros/rn/testavatar/node_modules/babel-core/lib/transformation/file/index.js:141:24)
>     at Pipeline.transform (/Users/perros/rn/testavatar/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
>     at transform (/Users/perros/rn/testavatar/node_modules/react-native/packager/transformer.js:108:26)
> TransformError: /Users/perros/rn/testavatar/node_modules/react-avatar/lib/index.js: Unknown plugin "transform-runtime" specified in "/Users/perros/rn/testavatar/node_modules/react-avatar/.babelrc" at 0, attempted to resolve relative to "/Users/perros/rn/testavatar/node_modules/react-avatar"
`

5. `cd node_modules` and then `cd react-avatar`. Then `npm install`
During installation I get these errors:
>`npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build      toolchain, use it instead!
  >npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
  >npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a  RegExp DoS issue
  > npm WARN prefer global marked@0.3.6 should be installed with -g

  > spawn-sync@1.0.15 postinstall /Users/perros/rn/testavatar/node_modules/react-    native/node_modules/spawn-sync
  > node postinstall
`
6. run `npm run dev`
I get these errors: 
>npm ERR! Darwin 15.5.0
>npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "run" "dev"
>npm ERR! node v6.6.0
>npm ERR! npm  v3.10.8

>npm ERR! missing script: dev
>npm ERR! 
>npm ERR! If you need help, you may report this error at:
>npm ERR!     <https://github.com/npm/npm/issues>

>npm ERR! Please include the following file with any support request:
>npm ERR!     /Users/perros/rn/testavatar/node_modules/react-native/npm-debug.log

7. cd back to project's directory and run `react-native run-ios`
 I get the same errors as step 3 above

**Comment by Sitebase** [comment]
@perrosnk I was not using `react-native`. It's probably best that someone else with react native experience takes a look at this.

**Comment by perrosnk** [comment]
@Sitebase It will be very nice if this could work with react native. There is no package in react-native that can provide a letter avatar. I believe it would become pretty popular too.

**Comment by JorgenEvens** [comment]
If there is someone else who would like to look into this we are happy to accept a PR.

**Comment by sturmenta-settle** [comment]
this problem when try to install on react-native

<img width="462" alt="Screenshot 2023-02-24 at 13 23 38" src="https://user-images.githubusercontent.com/119363738/221233104-2bfbc197-15de-4864-9b28-0c6473b51352.png">
